(sdl-init)
(sdl-img-init)
((lambda (win)
   ((lambda (blender eve)
      ((if*
        (lambda (x) x)
        (lambda (duck)
          ((lambda (loop)
             (loop loop))
           (lambda (loop)
             (sdl-event-poll eve)
             ((if*
               (lambda (type) (equal? type 256))
               (lambda (_) #f)
               (lambda (_)
                 (sdl-renderer-clear blender)
                 (sdl-renderer-copy blender duck '() '(0 0 50 50))
                 (sdl-renderer-present blender)
                 (loop loop)))
              (sdl-event-get-type eve)))))
        (lambda (_)
          (print _)
          (print "could not load image")))
       (sdl-load-texture blender "Duck.jpg"))
      (sdl-destroy-renderer blender)
      (sdl-destroy-window win))
    (sdl-create-renderer win)
    (sdl-create-event)))
 (sdl-create-window "Juhuuu" 100 100 500 500))

